[auth]
# Optionale API-Key-Quelle. Klartextspeicherung ist riskant!
# api_key = "sk-..."
# api_key_file = "pfad/zur/api_key.txt"

[models]
# IDs der zu verwendenden OpenAI‑Modelle. Sie werden in `app.openai_client`
# gelesen und bestimmen, welche Endpunkte für Klassifikation und Fragenantworten
# angesprochen werden.
label_model = "gpt-4o-mini"       # für Segment-Klassifikation in `pipeline.classify`
qa_model    = "gpt-4o"            # Modell für QA-Generierung; "o4-mini" ist eine schnellere Alternative
use_json_mode = true               # steuert JSON-Modus in `openai_client`; nötig für strukturierte Antworten
max_parallel_requests = 3          # maximale gleichzeitige API-Aufrufe in `openai_client`

[chunking]
# Steuergrößen für die Textsegmentierung in `app.chunking.split_into_chunks`.
# Anpassungen wirken sich direkt auf die Größe der an OpenAI gesendeten Textstücke aus.
target_tokens = 600          # Zielanzahl Tokens pro Chunk; größer = weniger, aber längere API-Calls
overlap_tokens = 60          # Anzahl Tokens Überlappung zwischen Chunks; erhöht Kontext bei QA
max_chars_per_chunk = 4000   # harte Obergrenze pro Chunk, falls Token-Schätzer fehlt

[prompting]
# Vorgaben für die Fragenerzeugung in `pipeline.generate_cards` und
# `openai_client.gen_qa_for_chunk`.
language = "de"              # Sprache der Fragen/Antworten, z.B. "de", "en" oder "fr"
tone = "sachlich, prüfungsorientiert, präzise"  # zusätzlicher Tonfall für die System-Prompts
max_questions_per_chunk_default = 8  # Begrenzung, wird von der GUI als Startwert gelesen

[costs]
# Preisangaben (USD pro 1 Mio Tokens) für die Kostenschätzung in
# `pipeline.estimate_cost`. Werte können bei neuen Modellen angepasst werden.

# GPT-4o
gpt-4o_input_usd_per_mtok = 5.0
gpt-4o_cached_input_usd_per_mtok = 0.5
gpt-4o_output_usd_per_mtok = 15.0

# GPT-4o Mini
gpt-4o-mini_input_usd_per_mtok = 0.15
gpt-4o-mini_cached_input_usd_per_mtok = 0.015
gpt-4o-mini_output_usd_per_mtok = 0.6

# o4 Mini (Alternative für Klassifikation)
o4-mini_input_usd_per_mtok = 2.0
o4-mini_cached_input_usd_per_mtok = 0.2
o4-mini_output_usd_per_mtok = 8.0

[ui]
# Darstellungsthema für die Tkinter-Oberfläche in `app.gui`.
theme = "auto"    # "auto" | "light" | "dark"

