#
# GSA Lernkarten – Konfiguration
# Hinweis:
#  - UTF-8 ohne BOM speichern
#  - Strings in "Anführungszeichen"
#  - Dezimalpunkt statt Komma
#  - Diese Datei überschreibt interne Defaults
#

[auth]
# Leer lassen, wenn der Key in der GUI gesetzt wird – sonst hier eintragen.
# Beispiel: api_key = "sk-..."
api_key = ""

[models]
# Wähle hier die real verfügbaren Modell-IDs deines Accounts.
# Du möchtest nicht auf GPT-4 zurückfallen, daher reine GPT-5-Familie:
#  - main: großes Standardmodell
#  - mini: schneller & günstiger
#  - nano: sehr günstig / leichte Tasks
main = "gpt-5"
mini = "gpt-5-mini"
nano = "gpt-5-nano"

# Optional: weitere Feature-Flags (falls im Code ausgewertet)
#thinking = true
#temperature = 0.2

[ui]
# Oberflächenbezogene Defaults (falls genutzt)
theme = "auto"     # "light" | "dark" | "auto"
language = "de"    # "de" | "en"
