[tool.ruff]
line-length = 100
target-version = "py310"
extend-select = ["E", "F", "I", "UP", "B"]
ignore = ["E203"]

[tool.pytest.ini_options]
addopts = "-q"
python_files = ["test_*.py", "*_test.py", "tests/*.py"]
