name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -U pip pytest ruff mypy coverage
      - name: Lint
        run: ruff check app tests
      - name: Type check
        run: mypy app
      - name: Tests (coverage)
        run: coverage run -m pytest && coverage xml && coverage report -m
